In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\KING INFOTECH\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
dataset = pd.read_csv(r"D:\HDFC loan dataset (2)\HDFC loan dataset\Loan payments data.csv")

In [4]:
dataset.head()

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,xqd20166231,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/14/2016 19:31,NaN,45,High School or Below,male
1,xqd20168902,PAIDOFF,1000,30,9/8/2016,10/7/2016,10/7/2016 9:00,NaN,50,Bechalor,female
2,xqd20160003,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/25/2016 16:58,NaN,33,Bechalor,female
3,xqd20160004,PAIDOFF,1000,15,9/8/2016,9/22/2016,9/22/2016 20:00,NaN,27,college,male
4,xqd20160005,PAIDOFF,1000,30,9/9/2016,10/8/2016,9/23/2016 21:36,NaN,28,college,female

In [5]:
dataset.tail()

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
495,xqd20160496,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/14/2016 19:08,3.0,28,High School or Below,male
496,xqd20160497,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,10/10/2016 20:02,14.0,26,High School or Below,male
497,xqd20160498,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,9/29/2016 11:49,3.0,30,college,male
498,xqd20160499,COLLECTION_PAIDOFF,1000,30,9/12/2016,11/10/2016,11/11/2016 22:40,1.0,38,college,female
499,xqd20160500,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/19/2016 11:58,8.0,28,High School or Below,male

In [6]:
dataset.isnull().sum()

Loan_ID             0
loan_status         0
Principal           0
terms               0
effective_date      0
due_date            0
paid_off_time     100
past_due_days     300
age                 0
education           0
Gender              0
dtype: int64

In [7]:
dataset.isnull().sum().sum()

np.int64(400)

In [8]:
dataset["past_due_days"] = dataset["past_due_days"].fillna(dataset["past_due_days"].mode()[0])

In [10]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Loan_ID         500 non-null    str
 1   loan_status     500 non-null    str
 2   Principal       500 non-null    int64
 3   terms           500 non-null    int64
 4   effective_date  500 non-null    str
 5   due_date        500 non-null    str
 6   paid_off_time   400 non-null    str
 7   past_due_days   500 non-null    float64
 8   age             500 non-null    int64
 9   education       500 non-null    str
 10  Gender          500 non-null    str
dtypes: float64(1), int64(3), str(7)
memory usage: 76.5 KB

In [11]:
# past_due_days m sbse repeat hone wale values is 59
(dataset["past_due_days"].mode()[0])

np.float64(59.0)

In [12]:
dataset.shape

(500, 11)

In [13]:
dataset.head()

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,xqd20166231,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/14/2016 19:31,59.0,45,High School or Below,male
1,xqd20168902,PAIDOFF,1000,30,9/8/2016,10/7/2016,10/7/2016 9:00,59.0,50,Bechalor,female
2,xqd20160003,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/25/2016 16:58,59.0,33,Bechalor,female
3,xqd20160004,PAIDOFF,1000,15,9/8/2016,9/22/2016,9/22/2016 20:00,59.0,27,college,male
4,xqd20160005,PAIDOFF,1000,30,9/9/2016,10/8/2016,9/23/2016 21:36,59.0,28,college,female

In [15]:
dataset.select_dtypes(include = "object")

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\2517536635.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dataset.select_dtypes(include = "object")

,Loan_ID,loan_status,effective_date,due_date,paid_off_time,education,Gender
0,xqd20166231,PAIDOFF,9/8/2016,10/7/2016,9/14/2016 19:31,High School or Below,male
1,xqd20168902,PAIDOFF,9/8/2016,10/7/2016,10/7/2016 9:00,Bechalor,female
2,xqd20160003,PAIDOFF,9/8/2016,10/7/2016,9/25/2016 16:58,Bechalor,female
3,xqd20160004,PAIDOFF,9/8/2016,9/22/2016,9/22/2016 20:00,college,male
4,xqd20160005,PAIDOFF,9/9/2016,10/8/2016,9/23/2016 21:36,college,female
...,...,...,...,...,...,...,...
495,xqd20160496,COLLECTION_PAIDOFF,9/12/2016,10/11/2016,10/14/2016 19:08,High School or Below,male
496,xqd20160497,COLLECTION_PAIDOFF,9/12/2016,9/26/2016,10/10/2016 20:02,High School or Below,male
497,xqd20160498,COLLECTION_PAIDOFF,9/12/2016,9/26/2016,9/29/2016 11:49,college,male
498,xqd20160499,COLLECTION_PAIDOFF,9/12/2016,11/10/2016,11/11/2016 22:40,college,female
499,xqd20160500,COLLECTION_PAIDOFF,9/12/2016,10/11/2016,10/19/2016 11:58,High School or Below,male

In [16]:
dataset.select_dtypes(include = "object").isnull()

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\1960488201.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dataset.select_dtypes(include = "object").isnull()

,Loan_ID,loan_status,effective_date,due_date,paid_off_time,education,Gender
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False

In [17]:
dataset.select_dtypes(include = "object").isnull().sum()

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\1690164646.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dataset.select_dtypes(include = "object").isnull().sum()

Loan_ID             0
loan_status         0
effective_date      0
due_date            0
paid_off_time     100
education           0
Gender              0
dtype: int64

In [19]:
dataset.select_dtypes(include = "object").isnull().sum().sum()

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\1146930851.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dataset.select_dtypes(include = "object").isnull().sum().sum()

np.int64(100)

In [21]:
dataset.select_dtypes(include = "object").isnull().columns

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\3305568807.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dataset.select_dtypes(include = "object").isnull().columns

Index(['Loan_ID', 'loan_status', 'effective_date', 'due_date', 'paid_off_time',
       'education', 'Gender'],
      dtype='str')

In [24]:
for i in dataset.select_dtypes(include = "object").isnull().columns:
    print(i)

Loan_ID
loan_status
effective_date
due_date
paid_off_time
education
Gender

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\1486437262.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in dataset.select_dtypes(include = "object").isnull().columns:

In [25]:
for i in dataset.select_dtypes(include = "object").isnull().columns:
    dataset[i] = dataset[i].fillna(dataset[i].mode()[0])

C:\Users\KING INFOTECH\AppData\Local\Temp\ipykernel_13104\3649153053.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in dataset.select_dtypes(include = "object").isnull().columns: